### ISSUE TITLE
I can got voice and data from BM to Mumble , but Can NOT send voice/data to BM, no logs and no voice to BM TG

### ISSUE THREAD

**Issue by bi7jta** [redfast00/dmr-brandmeister#2]
Hello ON3WPI

Thank you very much for your great project， I  plan to use your project bridge DMR and Mumble, I got problem follow your guide .

I can got voice and data from BM to Mumble success , but Can NOT send voice/data to BM, no logs and no voice  from Mumble to BM TG

I use Visualbox in macOS, maybe the problem in VisualBox, I will use Raspberry Pi 4B follow you guide again.

I am very eager to use this project to complete my Mumble App connection.

By the way , do you consider write a Bridge to Mumble like DVSwitch doing?

Thank you again!

```
lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 23.04
Release:        23.04
Codename:       lunar

{
	"serverHost": "47.100.76.205",
	"serverPort": 54006,
	"serverPassword": "******",
	"serverTimeoutSeconds": 20,
	"appID": 460****,
	"recTalkgroupID": 46001,
    "callHangTimeSeconds": 50,
	"callExecCommand1": "cat",
	"callExecCommand1ShowStderr": false,
	"callExecCommand2": "",
	"callExecCommand2ShowStderr": false,
	"callExecCommand3": "",
	"callExecCommand3ShowStderr": false,
	"outputDir": "test",
	"outputFileExtension": "ambe",
	"createDailyAggregateFile": true,
	"mumble" : {
		"server": "192.168.2.33",
		"username": "DMR-bot",
		"password": "",
		"channel": "Mumble2DMR",
		"fifo": "/tmp/dmr.fifo"
	}
}

```
Screenshots:

![image](https://github.com/redfast00/brandmeister-dmr-opendmr/assets/22002824/9929f993-ef07-4913-a277-2d28500ebe96)

![image](https://github.com/redfast00/brandmeister-dmr-opendmr/assets/22002824/592aa646-33f5-4c42-8fbe-b39e2878b8c1)

![image](https://github.com/redfast00/brandmeister-dmr-opendmr/assets/22002824/31f333a9-568c-4e55-91ae-7d442a2f9bdd)

**Comment by redfast00** [comment]
> I can got voice and data from BM to Mumble success , but Can NOT send voice/data to BM, no logs and no voice from Mumble to BM TG

Correct, see the README of https://github.com/redfast00/brandmeister-dmr-sea:

> # Can I also talk in Mumble and have the bridge send it to the Brandmeister network?
> No: this is too easy to misconfigure so that unlicensed users could transmit, possibly breaking some laws while doing so.
